### ISSUE TITLE
Godwoken v1 Web3 RPC: eth_getBlockByNumber -> Internal error

### ISSUE THREAD

**Issue by Flouse** [nervosnetwork/godwoken-web3#184]
```bash
> curl https://godwoken-testnet-web3-v1-rpc.ckbapp.dev/ -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params": ["0x0",false],"id":1}' 

{"jsonrpc":"2.0","id":1,"error":{"code":-32603,"message":"Internal error"}}
```

**Comment by zmcNotafraid** [comment]
解析数据的时候有这么一种交易 {"raw":{"from_id":"0x2","to_id":"0x4","nonce":"0x3","args":"0x03000000380000000c0000003000000001000000e88439c2410c2bd7c3556b7fa0964a829cc9001807ddb00dad58bb274ae5f98a0000000000000000"}
之前处理v0 的时候没遇到过，请问这种是什么类型的交易？如何解析

**Comment by RetricSu** [comment]
the database table has some problem, should be fixed soon
