### ISSUE TITLE
About `ETH Address Registry` Layer2 Contract

### ISSUE THREAD

**Issue by Flouse** [nervosnetwork/godwoken-web3#185]
解析608区块数据的时候有这么一种交易{"raw":{"from_id":"0x2","to_id":"0x3","nonce":"0x2","args":"0x03000000380000000c00000030000000010000006e45d598f56e7d81eaf1f918fe8178e18cfdf9fef0ef7cb75bfac5b5ea69c1b40000000000000000"}

之前处理v0 的时候没遇到过，请问这种是什么类型的交易？如何解析？

_Originally posted by @zmcNotafraid in https://github.com/nervosnetwork/godwoken-web3/issues/184#issuecomment-1056858662_

**Comment by Flouse** [comment]
ETH Address Registry account id: 4

## Contract Code 
https://github.com/nervosnetwork/godwoken-polyjuice/blob/compatibility-breaking-changes/c/eth_addr_reg.c

## Related PR
- https://github.com/nervosnetwork/godwoken-polyjuice/pull/113

**Comment by zmcNotafraid** [comment]
> # Godwoken testnet_v1
> ETH Address Registry account id: 4
> 
> ## Contract Code
> https://github.com/nervosnetwork/godwoken-polyjuice/blob/compatibility-breaking-changes/c/eth_addr_reg.c
> 
> ## Molecule
> https://github.com/nervosnetwork/godwoken/blob/compatibility-breaking-changes/crates/types/schemas/godwoken.mol#L359-L385
> 
> ## Related PR
> * [BREAKING CHANGE: support native eth_address by the `ETH Address Registry` layer2 contract godwoken-polyjuice#113](https://github.com/nervosnetwork/godwoken-polyjuice/pull/113)
> 
> @zmcNotafraid

Got it! Thank you

**Comment by Flouse** [comment]
We could get creator_id from `poly_getCreatorId` RPC, and then get the `ETH Address Registry ID` from creator account script args.

see: https://github.com/nervosnetwork/godwoken/blob/compatibility-breaking-changes/crates/tools/src/create_creator_account.rs#L151-L153

**Comment by Flouse** [comment]
ETH Address Registry ID: 4
ETH Address Registry layer2 contract introduces two-ways mappings between eth_address and gw_script_hash.

see: https://github.com/nervosnetwork/godwoken-info/tree/main/testnet_v1
