### ISSUE TITLE
eth_getTransactioniReceipt return null

### ISSUE THREAD

**Issue by zmcNotafraid** [nervosnetwork/godwoken-web3#208]
```
curl https://godwoken-testnet-web3-v1-rpc.ckbapp.dev -X POST -H "Content-Type: application/json" \             
  -d '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params": ["0xf6cbd7ee5d8b8a3c4109729a3ec9044bb22703c6febc1dfe179a78e092ccd6bf"],"id":1}'
{"jsonrpc":"2.0","id":1,"result":null}%                                
```
updated:
I test some of txs's eth_getTransactioniReceipt rpc, and all of them return null

**Comment by classicalliu** [comment]
Is "all return null" means all transaction returns null ?
And transaction of `0xf6cbd7ee5d8b8a3c4109729a3ec9044bb22703c6febc1dfe179a78e092ccd6bf` is a succeed transaction?

**Comment by zmcNotafraid** [comment]
> Is "all return null" means all transaction returns null ? And transaction of `0xf6cbd7ee5d8b8a3c4109729a3ec9044bb22703c6febc1dfe179a78e092ccd6bf` is a succeed transaction?

I test some of txs's eth_getTransactioniReceipt rpc, and all of them return null
like this also return null:
```
curl https://godwoken-testnet-web3-v1-rpc.ckbapp.dev -X POST -H "Content-Type: application/json" \             
  -d '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params": ["0x7b6bcaf2f680c1841840b1bc76a51f7d4729ae2dc3dab878262f11b446c841f5"],"id":1}'
{"jsonrpc":"2.0","id":1,"result":null}%   
```

**Comment by classicalliu** [comment]
I find a success one `0xb5c9636c01d6925b8f9e95d183c2f9dd5a2c533a4cad806f6a8517060d47dc8c`, so I wonder to know the transaction's status of you test, they are success transactions or failed transactions ?

**Comment by Flouse** [comment]
I think `0xb5c9636c01d6925b8f9e95d183c2f9dd5a2c533a4cad806f6a8517060d47dc8c` is a eth_tx_hash, 
while `0xf6cbd7ee5d8b8a3c4109729a3ec9044bb22703c6febc1dfe179a78e092ccd6bf` is a gw_tx_hash.

Related PR
- https://github.com/nervosnetwork/godwoken-web3/pull/172

Related issue:
- https://github.com/nervina-labs/godwoken_explorer/issues/276

**Comment by zmcNotafraid** [comment]
My fault. I use wrong tx_hash. Thanks!

**Comment by dxnght** [comment]
@Flouse 
Can confirm some strange things here: 
TxHash from contract interaction returns null

context:

```
const method =
      deployedContractInst.methods.transfer(
        '0x66452d81a51411F8d4CE1eeF004377eEB52bf65a',
        10
      )

const transaction = {
      nonce: await web3.eth.getTransactionCount(account.address),
      from: account.address,
      gas: 1000000000000002,
      gasPrice: '100',
      to: method._parent._address,
      data: method.encodeABI(),
    }

// account - web3's Account (from private key)
const { rawTransaction } = await account.signTransaction(transaction)

const txReceipt = await web3.eth.sendSignedTransaction(rawTransaction)

```


```
{
    "jsonrpc": "2.0",
    "id": 17,
    "method": "eth_sendRawTransaction",
    "params": ["0xf8b68204606487038d7ea4c680029486e026e9a8b1cb2d64aeaba75547ab4c44b1f1c38405f5e100b844a9059cbb00000000000000000000000066452d81a51411f8d4ce1eef004377eeb52bf65a000000000000000000000000000000000000000000000000000000000000000a87062bb600000030a01939820fd0257795f5f44c3dce96c65013487c1cd2b5cea11088a7cbf903abfba0678647d4d04c83c62d043e5c4b3a1a9e8ac11f3deb9de14f6025c5ca0d33073d"]
}

{
    "jsonrpc": "2.0",
    "id": 17,
    "result": "0x28ca43cba508d28b53e78b1342207d5e3b9d39553614ecd465314b84f54bc239"
}
```

> gw_get_transaction_receipt also returns null

I'm expecting that all is fine because balanceOf(account.address) is gotten

<img width="861" alt="image" src="https://user-images.githubusercontent.com/33819269/158810577-873e17c6-7cd9-42ac-951f-f89c240c08b7.png">
