### ISSUE TITLE
v1: no log in transaction receipt 

### ISSUE THREAD

**Issue by Flouse** [nervosnetwork/godwoken-web3#209]
[](https://cdn.discordapp.com/attachments/953170275472662531/953573949894185010/contract.png)when i transfer token to my contract, it will call receive function and emit logs. the problem is there isn't log in transaction receipt

![image](https://user-images.githubusercontent.com/1297478/158556498-cd152ae0-33d9-401d-a1df-d7c48c4909ba.png)
![image](https://user-images.githubusercontent.com/1297478/158556569-74f8177d-abaa-4fb6-973d-f04f5ae66bd9.png)

**Comment by Liyw-liyw** [comment]
tx_hash: 0x583d90754788b157691e144f6c184f9c4ec61c9ffe4c0768b8ddd7eec4e39f9e
full contract code link: https://develop.chainide.com/s/nervos/a16fe975822448d9a098fdd7f7208c72?open=src/RiverMenGift.sol&type=file

**Comment by Flouse** [comment]
Hi, @Liyw-liyw 
I can't open the `full contract code link`:
![image](https://user-images.githubusercontent.com/1297478/158731502-f98b6520-68f3-4524-a5eb-8f4e82bd7256.png)

**Comment by classicalliu** [comment]
Hello, @Liyw-liyw 

How do you transfer token to contract ?

**Comment by Liyw-liyw** [comment]
![image](https://user-images.githubusercontent.com/62988648/159197547-a4095ad8-b03b-4c46-b50a-32f9c5ef3856.png)

i transfer ckb to contract by calldata. it will call contract received function

**Comment by Flouse** [comment]
- Should be fixed in [godwoken-prebuilds v1.2-rc](https://github.com/nervosnetwork/godwoken-docker-prebuilds/pkgs/container/godwoken-prebuilds/26181794?tag=1.2-rc)
   "ref.component.godwoken-polyjuice": "[1.2.0](https://github.com/nervosnetwork/godwoken-polyjuice/releases/tag/1.2.0)  b1e0622"

- deployed on [testnet_v1](https://github.com/nervosnetwork/godwoken-info/tree/main/testnet_v1_1): https://godwoken-testnet-v1.ckbapp.dev
