### ISSUE TITLE
v1: to id missing

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnetwork/godwoken-web3#216]
env:  docker image:ghcr.io/nervosnetwork/godwoken-web3-prebuilds:compatibility-breaking-changes-1a52afb 

Errors that occur when calling the rpc interface frequently
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/32102187/158921145-f9f00e10-b7a2-4570-bde2-975b0900d471.png">

**Comment by gpBlockchain** [comment]
<img width="1324" alt="image" src="https://user-images.githubusercontent.com/32102187/158922430-c683adff-7a7a-4cca-aef3-cac12d7cb425.png">

**Comment by RetricSu** [comment]
> env: docker image:ghcr.io/nervosnetwork/godwoken-web3-prebuilds:compatibility-breaking-changes-1a52afb
> 
> Errors that occur when calling the rpc interface frequently <img alt="image" width="1128" src="https://user-images.githubusercontent.com/32102187/158921145-f9f00e10-b7a2-4570-bde2-975b0900d471.png">

is there by any chance you are using metamask? metamask will call some ENS contract automatically which does not exits on godwoken. 

if not, what is is the contract you are calling with? this error usually means the calling contract does not exits.

**Comment by RetricSu** [comment]
```sh
[1] [error]  JSONRPC Server Error: [bound call] RpcError: to id missing! toAddress: 0x44691B39d1a75dC4E0A0346CBB15E310e6ED1E86 RpcError: to id missing! toAddress: 0x44691B39d1a75dC4E0A0346CBB15E310e6ED1E86
```

while the `0x44691B39d1a75dC4E0A0346CBB15E310e6ED1E86` is https://etherscan.io/address/0x44691b39d1a75dc4e0a0346cbb15e310e6ed1e86#code

> is there by any chance you are using metamask? metamask will call some ENS contract automatically which does not exits on godwoken.

similar behavior, while not ENS contract but parity signature register contract. https://www.bokconsulting.com.au/blog/a-quick-look-at-paritys-signature-registry-contract/  it looks like some sort of smart contract method signature record? anyway, this should not effect the deployment on e2e test so I am closing for now, if you got more question feel free to re-open.
