### ISSUE TITLE
v1:duplicate key value violates unique constraint "blocks_pkey"

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnetwork/godwoken-web3#217]
env: ghcr.io/nervosnetwork/godwoken-web3-indexer-prebuilds:compatibility-breaking-changes-1a52afb
Use `hardhat` to send contract transactions frequently, and the `gw-web3-indexer` reports an error when synchronizing data, causing the process to exit abnormally
<img width="841" alt="image" src="https://user-images.githubusercontent.com/32102187/158925613-f32578f6-4879-4c67-bea1-7466aa53c475.png">
<img width="1345" alt="image" src="https://user-images.githubusercontent.com/32102187/158925632-e513dbdd-ba59-4fa5-a7ff-99b6692e2e3e.png">
There are also some exception logs, I don't know if it is a problem
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/32102187/158925778-d81e00ce-8c3c-40a1-8df8-93c87c7a0065.png">

**Comment by Flouse** [comment]
fix(indexer): Panic if return data is empty
https://github.com/nervosnetwork/godwoken-web3/pull/211

Images：
ghcr.io/nervosnetwork/godwoken-web3-indexer-prebuilds:compatibility-breaking-changes-94e2025

Would you update the image and try again?
thanks!

**Comment by gpBlockchain** [comment]
> fix(indexer): Panic if return data is empty
> 
> * [fix(indexer): Panic if return data is empty #211](https://github.com/nervosnetwork/godwoken-web3/pull/211)
> 
> Images： ghcr.io/nervosnetwork/godwoken-web3-indexer-prebuilds:compatibility-breaking-changes-94e2025
> 
> Would you update the image and try again? thanks!
this image has the same problem 
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/32102187/158939081-5d742d71-84c2-4382-b540-0d50cfd4fa9b.png">

**Comment by gpBlockchain** [comment]
Steps to reproduce
- prepare godwoken env
- use hardhat send tx until gw_web3_indexer exitd
```
git clone -b issue217  https://github.com/gpBlockchain/gw-evm-opcode-test.git
cd gw-evm-opcode-test
npm install
npm test
```

**Comment by classicalliu** [comment]
Hello, @gpBlockchain 
Which version(git commit) of kicker do you use ?

**Comment by gpBlockchain** [comment]
> Hello, @gpBlockchain Which version(git commit) of kicker do you use ?

6615604076c9cc267f3606016a094f0475fb5dcc

**Comment by classicalliu** [comment]
Hello

It caused by the bug of kicker
- https://github.com/RetricSu/godwoken-kicker/pull/195

Please update and try again, thanks
