### ISSUE TITLE
v1: TxHash from contract interaction returns null

### ISSUE THREAD

**Issue by Flouse** [nervosnetwork/godwoken-web3#218]
Can confirm some strange things here: 
TxHash from contract interaction returns null

context:

```
const method =
      deployedContractInst.methods.transfer(
        '0x66452d81a51411F8d4CE1eeF004377eEB52bf65a',
        10
      )

const transaction = {
      nonce: await web3.eth.getTransactionCount(account.address),
      from: account.address,
      gas: 1000000000000002,
      gasPrice: '100',
      to: method._parent._address,
      data: method.encodeABI(),
    }

// account - web3's Account (from private key)
const { rawTransaction } = await account.signTransaction(transaction)

const txReceipt = await web3.eth.sendSignedTransaction(rawTransaction)

```

```
{
    "jsonrpc": "2.0",
    "id": 17,
    "method": "eth_sendRawTransaction",
    "params": ["0xf8b68204606487038d7ea4c680029486e026e9a8b1cb2d64aeaba75547ab4c44b1f1c38405f5e100b844a9059cbb00000000000000000000000066452d81a51411f8d4ce1eef004377eeb52bf65a000000000000000000000000000000000000000000000000000000000000000a87062bb600000030a01939820fd0257795f5f44c3dce96c65013487c1cd2b5cea11088a7cbf903abfba0678647d4d04c83c62d043e5c4b3a1a9e8ac11f3deb9de14f6025c5ca0d33073d"]
}

{
    "jsonrpc": "2.0",
    "id": 17,
    "result": "0x28ca43cba508d28b53e78b1342207d5e3b9d39553614ecd465314b84f54bc239"
}
```

> gw_get_transaction_receipt also returns null

I'm expecting that all is fine because balanceOf(account.address) is gotten

<img width="861" alt="image" src="https://user-images.githubusercontent.com/33819269/158810577-873e17c6-7cd9-42ac-951f-f89c240c08b7.png">

_Originally posted by @dxnght in https://github.com/nervosnetwork/godwoken-web3/issues/208#issuecomment-1070910309_

**Comment by RetricSu** [comment]
we check the log and found that, the eth tx `0x28ca43cba508d28b53e78b1342207d5e3b9d39553614ecd465314b84f54bc239` should be mapping with the gw_tx_hash `0xd599efdba23206a6cf8cff38155501295315e0697a4d16110f53bace3ab561ee`, and this transaction was failed with `invalid exit code 2`, which means a revert error.
