### ISSUE TITLE
withdrawal lock args can't parse with godwoken molecule

### ISSUE THREAD

**Issue by zmcNotafraid** [nervosnetwork/godwoken-web3#222]
https://explorer.nervos.org/aggron/transaction/0xb8ca4914b92285d8f2b2ba7fa2a3a2ff7610f174623b5dc0e585917c7272f1b7 output index#2 is a withdrawal lock.
But args can't parse with https://github.com/nervosnetwork/godwoken/blob/90ecd3b58e1f25fe83ef74090e5bca83287ca2eb/crates/types/schemas/godwoken.mol#L196 molecule struct

**Comment by Flouse** [comment]
I think there is `owner_lock` info following the WithdrawalLockArgs.
see: **[verify_finalized_owner_lock](https://github.com/nervosnetwork/godwoken/blob/90ecd3b58e1f25fe83ef74090e5bca83287ca2eb/crates/rpc-client/src/withdrawal.rs#L36-L71) function**

**Comment by zmcNotafraid** [comment]
Got it. After remove the owner_lock info I can parse the withdrawal  lock args
