### ISSUE TITLE
What is the type of this transaction?

### ISSUE THREAD

**Issue by zmcNotafraid** [nervosnetwork/godwoken-web3#225]
I don't know how to parse the args.

``
curl https://godwoken-testnet-web3-v1-rpc.ckbapp.dev -X POST -H "Content-Type: application/json" \
  -d '{"jsonrpc":"2.0","method":"gw_get_transaction","params": ["0x718ef966e73ffa27a2c94ca7d0367d415b5ca4fbc94fc7ef137e25d9f7653639"],"id":1}'
```

`{"jsonrpc":"2.0","id":1,"result":{"transaction":{"raw":{"from_id":"0x2e8","to_id":"0x4","nonce":"0x3e","args":"0x020000004f2548c2e3e8776ec3fc272f69c18c866ea435d7cc7f53ef92550e7273d2a7920000000000000000"},"signature":"0x8a8faa8fc45e3669f0ab01a8ca63191ba3022cb94d45dc11e11f6672a86ebc4a071f06e1b657408ab6e92986b558f3451c126acf3d94d6389e604903566e88f201","hash":"0x718ef966e73ffa27a2c94ca7d0367d415b5ca4fbc94fc7ef137e25d9f7653639"},"status":"committed"}}%   `

**Comment by Flouse** [comment]
"to_id":"0x4"
ETH Address Registry account id: 4

see: https://github.com/nervosnetwork/godwoken-info/pull/20/files#diff-0b45e34d58832d8183c8661473eab29e73d670cf7341ca362cba5ce138284c76R38-R39

**Comment by zmcNotafraid** [comment]
Got it.I confused with polyjuice creator id.
