### ISSUE TITLE
Request gw rpc "gw_execute_raw_l2transaction" error message: JSONRPCError

### ISSUE THREAD

**Issue by Dawn-githap** [nervosnetwork/godwoken-web3#232]
env: docker image: ghcr.io/nervosnetwork/godwoken-web3-prebuilds:compatibility-breaking-changes-1a52afb

solidity code：
```
    function ass(uint256 b2, uint256 cc1, uint256 cc2) public view returns (bytes memory a, bytes memory b){
        assembly {
            a := mload(0x40)
            b := add(a, b2)
            codecopy(a, cc1, cc2)
        }
    }
```
invoke ass(33,4,32);
other blockchain return 
```
0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000040

error code：
[https://github.com/Dawn-githap/gw-hardhat-test.git](url)

error message：
```
11:40:11 0|gw-web3  | request.method: eth_call
11:40:11 0|gw-web3  | fromId: 2
11:40:11 0|gw-web3  | rawL2Transaction: {
11:40:11 0|gw-web3  |   "from_id": "0x2",
11:40:11 0|gw-web3  |   "to_id": "0x40",
11:40:11 0|gw-web3  |   "nonce": "0x0",
11:40:11 0|gw-web3  |   "args": "0xffffff504f4c59000000000100000000010000000000000000000000000000000000000000000000000000000000000004000000e08c3988"
11:40:11 0|gw-web3  | }
11:40:11 0|gw-web3  | Call gw rpc "gw_execute_raw_l2transaction" error: JSONRPCError: server error {"code":-32600,"message":"invalid exit code 50","data":{"tx_hash":"0xe17c2fe31c9d74a391237cd21f8fdca062a5c2f012cb3330f491b2d128222e27","block_number":"0x194","return_data":"0x","last_log":{"account_id":"0x40","service_flag":"0x2","data":"0x6a950100000000006a95010000000000000000000000000000000000000000000000000000000000"}}}
11:40:11 0|gw-web3  | [error]  JSONRPC Server Error: [bound call] RpcError: success:  RpcError: success:
11:40:11 0|gw-web3  |     at Eth.call (/godwoken-web3/packages/api-server/lib/methods/modules/eth.js:331:19)
11:40:11 0|gw-web3  |     at runMicrotasks (<anonymous>)
11:40:11 0|gw-web3  |     at processTicksAndRejections (internal/process/task_queues.js:95:5)
11:40:11 0|gw-web3  |     at async Eth.call (/godwoken-web3/packages/api-server/lib/methods/validator.js:28:20)
11:40:11 0|gw-web3  |     at async Server.methods.<computed> (/godwoken-web3/packages/api-server/lib/methods/index.js:49:36)
```

**Comment by keroro520** [comment]
[The reproducing smart contract](https://github.com/gpBlockchain/gw-evm-opcode-test/blob/5a6067902b9b437d52bfe81311a135a657b6bfd6/contracts/opcodes/bug/BugContract.sol#L13):

  ```
  function add(uint256 b2, uint256 cc1, uint256 cc2) public view returns (bytes memory a, bytes memory b){
      assembly {
          a := mload(0x40)
          b := add(a, b2)
          codecopy(a, cc1, cc2)
      }
  }
  ```

The error code we receive from Godwoken and Godwoken-Web3 is [`GW_FATAL_BUFFER_OVERFLOW 50`](https://github.com/nervosnetwork/godwoken-scripts/blob/b1192328af2c7c43bed04fbe4e98943bd0b86d4e/c/gw_errors.h#L17) 

This error is throw by [`sys_set_program_return_data`](https://github.com/nervosnetwork/godwoken-scripts/blob/b1192328af2c7c43bed04fbe4e98943bd0b86d4e/c/generator_utils.h#L154-L157), indicates 25KB upper limit for return data:

```c
/* set call return data */
int sys_set_program_return_data(gw_context_t *ctx, uint8_t *data,
                                uint64_t len) {
  if (ctx == NULL) {
    return GW_FATAL_INVALID_CONTEXT;
  }
  if (len > GW_MAX_DATA_SIZE) {
    printf("Exceeded max return data size");
    return GW_FATAL_BUFFER_OVERFLOW;
  }
  return syscall(GW_SYS_SET_RETURN_DATA, data, len, 0, 0, 0, 0);
}
```

---

I try to implement a contract to locate the upper limit for return data on Hardhat localnet. My experiment's conclusion is `1785056`.

```
contract TestLimitForReturnData {
    function works_well() public view returns (bytes memory value) {
        value = new bytes(1785056);
        return value;
    }

    function works_bad() public view returns (bytes memory value) {
        value = new bytes(1785057);
        return value;
    }
}
```

After discussing with @jjy, I think the limit is reasonable. On the other hand, I think we should document these resource limits on the documentation for compatibility, e.g. return data, contract code, and contract storage.

**Comment by keroro520** [comment]
[The size limit for contract storage is `25KB` too](https://github.com/nervosnetwork/godwoken-scripts/blob/31293d1/c/validator_utils.h#L326-L329):

```c
/* Store data by data hash */
int sys_store_data(gw_context_t *ctx, uint64_t data_len, uint8_t *data) {
  if (ctx == NULL) {
    return GW_FATAL_INVALID_CONTEXT;
  }

  if (0 == data_len) {
    return 0;
  }
  if (data_len > GW_MAX_DATA_SIZE) {
    printf("Exceeded max store data size");
    return GW_FATAL_INVALID_DATA;
  }

..
```
