### ISSUE TITLE
deploy contract failed 

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnetwork/godwoken-web3#242]
env: https://github.com/RetricSu/godwoken-kicker.git
branch: compatibility-changes
commit: 76430974cc0b8f88e2bca659725cb8664d3b78d2
solodity code
```
pragma solidity ^0.6.10;

contract CrossCallBugTest{

    CrossCall1 cc;
    CrossCall1 cc1;

    constructor () public {
        cc = new CrossCall1();
        cc1 = new CrossCall1();
        cc.setOtherAddress(address(cc1));
        cc1.setOtherAddress(address(cc));
    }

    function call_stack(uint stackSize) public returns(uint256){
        return cc.call_stack(stackSize-1)+stackSize;
    }

}

contract CrossCall1{

    address  otherAddress;

    function setOtherAddress(address addr) public {
        otherAddress = addr;
    }

    function call_stack(uint stackSize) public returns(uint256){
        CrossCall1 cc = CrossCall1(otherAddress);
        if(stackSize<=0){
            return 1;
        }
        try cc.call_stack(stackSize-1) returns(uint256 num){
            return num+stackSize;
        }catch {
            return cc.call_stack{gas:100000}(stackSize-1);
        }
    }

}
```
1. deploy CrossCallBugTest contract  failed 
expected: deploy success
### actions
hardhat local net: https://github.com/gpBlockchain/gw-evm-opcode-test/runs/5733544282
gw net:https://github.com/gpBlockchain/gw-evm-opcode-test/runs/5733642755?check_suite_focus=true
### Reproduce the problem
1. fork  https://github.com/gpBlockchain/gw-evm-opcode-test.git
2. exec actions
<img width="411" alt="image" src="https://user-images.githubusercontent.com/32102187/160566953-4d2c75b5-5a1a-40ae-a15f-bbf0ffc4b86e.png">

**Comment by RetricSu** [comment]
outdated
