### ISSUE TITLE
eth_call should support zero (optional) "from" address

### ISSUE THREAD

**Issue by Dominator008** [nervosnetwork/godwoken-web3#246]
```
curl -X POST --data '{"jsonrpc":"2.0","id":73,"method":"eth_call","params":[{"data":"0xdd62ed3e00000000000000000000000029b563951ed0eb9ae5c49692266e1fbc81445cfe000000000000000000000000c01d5b3170c9cd146ab8ccbc210ce39e2892f48c","from":"0x0000000000000000000000000000000000000000","to":"0x696f8499f7cafdba66582d619d628f86ee95e5ba"},"latest"]}
' https://godwoken-testnet-web3-v1-rpc.ckbapp.dev -H "Content-Type: application/json"
```
returns error:
```json
{"jsonrpc":"2.0","id":73,"error":{"code":-32099,"message":"zero address 0x0000000000000000000000000000000000000000 has no valid account_id!"}}
```
However per the JSON-RPC spec the "from" address can be zero.

**Comment by RetricSu** [comment]
unfortunately we do not have the corresponding "zero address" concept in Godwoken. 

However, if the contract method in your `eth_call` has nothing to do with from address, you only want a "optional" one, you can leave it blank like this: 

`curl -X POST --data '{"jsonrpc":"2.0","id":73,"method":"eth_call","params":[{"data":"0xdd62ed3e00000000000000000000000029b563951ed0eb9ae5c49692266e1fbc81445cfe000000000000000000000000c01d5b3170c9cd146ab8ccbc210ce39e2892f48c","to":"0x696f8499f7cafdba66582d619d628f86ee95e5ba"},"latest"]}
' https://godwoken-testnet-web3-v1-rpc.ckbapp.dev -H "Content-Type: application/json"`

if from address do effect the method you are calling, I assume that from address must be exact the same with zero address in your case, which might be impossible on Godwoken.

**Comment by RetricSu** [comment]
unfortunately we do not have the corresponding "zero address" concept in Godwoken. 

However, if the contract method in your `eth_call` has nothing to do with from address, you only want a "optional" one, you can leave it blank like this: 

`curl -X POST --data '{"jsonrpc":"2.0","id":73,"method":"eth_call","params":[{"data":"0xdd62ed3e00000000000000000000000029b563951ed0eb9ae5c49692266e1fbc81445cfe000000000000000000000000c01d5b3170c9cd146ab8ccbc210ce39e2892f48c","to":"0x696f8499f7cafdba66582d619d628f86ee95e5ba"},"latest"]}
' https://godwoken-testnet-web3-v1-rpc.ckbapp.dev -H "Content-Type: application/json"`

if from address do effect the method you are calling, I assume that from address must be exact the same with zero address in your case, which might be impossible on Godwoken.

**Comment by Dominator008** [comment]
The zero address is filled in by the Go binding generated by go-ethereum. Currently we hack the request to work around the issue.
