### ISSUE TITLE
eth_getLogs not working correctly 

### ISSUE THREAD

**Issue by Roger-RumbleFish** [nervosnetwork/godwoken-web3#260]
When i try to run this query on godwoken testnet v1
`
curl -v -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"topics":["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"],"fromBlock":"0x90b3","toBlock":"0x90b4"}],"id":74}' https://godwoken-testnet-web3-v1-rpc.ckbapp.dev/ | jq
`
 I receive a event without topics. I shouldn't receive any events without topic if i put inside params a topic hash

**Comment by Kuzirashi** [comment]
I can confirm.
<img width="805" alt="image" src="https://user-images.githubusercontent.com/4950658/162236325-bbf6cf5f-407b-4850-bc3e-76d0ecaed273.png">

**Comment by RetricSu** [comment]
do you have any idea what contract is `0x4c26a5293121f072f10b677ab71efc5ab01917bd`? 

There seems to have a weird log record which has no topics in database, and it is produced by this [transaction](https://v1.aggron.gwscan.com/tx/0x8c675778ac7d2793843d2a0e89ec9697a9e178d42d7995a0fa24e15b54316a98), and you can see the input data from the transaction is `0x42791213`. 

If we can get the contract source code / the contract method calling from the input data, we might be able to get some clue why there is no topics.

**Comment by Roger-RumbleFish** [comment]
@RetricSu The problem is about filter. When i ask RPC to filter me logs with topic: 'some value' i want to receive events with only topics with some value and right now i receive topic without. The problem is not about empty topic but filter method

**Comment by RetricSu** [comment]
> @RetricSu The problem is about filter. When i ask RPC to filter me logs with topic: 'some value' i want to receive events with only topics with some value and right now i receive topic without. The problem is not about empty topic but filter method

I know, and this problem can be quick fixed with this pr https://github.com/nervosnetwork/godwoken-web3/pull/274 , However, I am looking for a more deep reason where the log should not be generated without any topics in the database.

**Comment by Roger-RumbleFish** [comment]
Unfortunately i have no idea

**Comment by RetricSu** [comment]
> Event without a topic is completely legit. It's a result of LOG0 opcode. It's not used very often, as there isn't direct way to use it from level of Solidity. However with inline assembly you can use it. This is the cheapest event there is on EVM, so it definitely has some merit to it.

thanks for providing such information!! I do not know that before. will adjust the [pr](https://github.com/nervosnetwork/godwoken-web3/pull/274) to consider for empty topics case as well.

**Comment by RetricSu** [comment]
the fixed code has been merged https://github.com/nervosnetwork/godwoken-web3/pull/274, and I have tested it on godwoken devnet. please wait for the deployment of the Godwoken v1.1 version on testnet.
