### ISSUE TITLE
MetaMask shows failed transactions as pending

### ISSUE THREAD

**Issue by Kuzirashi** [nervosnetwork/godwoken-web3#261]
When sending a transaction on Godwoken Testnet v1 that fails the transaction shows as "pending" in MetaMask and when you try to send another transaction it will give you problem about wrong nonce.

Because of this after failed transaction on Godwoken Testnet v1 MetaMask is stuck.

The workaround is to go to Settings > Advanced and click Reset Account in MetaMask.

I debugged MetaMask extension in Firefox and it seems after sending transaction:
1. MetaMask is waiting for new block
2. After new block is mined MetaMask tries to get transaction receipt

Eg. it's sending such request:
```
{"id":7536123498664,"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["METAMASK_TX_HASH"]}
```

MetaMask frozen after sendRawTransaction with transaction that will revert:
<img width="345" alt="image" src="https://user-images.githubusercontent.com/4950658/162464405-33b8b014-f331-4cea-9afa-adcad33ef74f.png">

Trying to send new transaction:
<img width="895" alt="image" src="https://user-images.githubusercontent.com/4950658/162470497-6013a754-3a0b-4b60-8904-caf6df208fc1.png">
```
MetaMask - RPC Error: [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32603,"data":{"code":-32602,"message":"JSONRPCError: server error {\"code\":-32001,\"message\":\"invalid nonce of account 181 expected 262, actual 263\"}"}}}' 
```

sendRawTransaction calling "artificialRevert" method:
```
pragma solidity >=0.8.0;

contract SimpleStorage {
  uint storedData;

  constructor() payable {
    storedData = 123;
  }

  function set(uint x) public payable {
    storedData = x;
  }

  function get() public view returns (uint) {
    return storedData;
  }

  function artificialRevert() public {
    require(true == false, "artificial revert");
    storedData = 777777;
  }
}
```

MetaMask request on Godwoken Testnet v1:
```
{"id":844131868751,"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xf86d82010601830f4240943f972ac67435ceb1304daaef77d97586eb7c54428084862d6eba87062bb60000002fa01ee7a2d1fa062686247578cb06146b5ad67810d5b2627d41e8e61bbdbc38b99ba06aece96800a91479b088fab5dab913033eeb523b067be79056ee5910c3685849"]}
```

response:
```
{"jsonrpc":"2.0","id":844131868751,"result":"0x7c943614e021a30e17b62053a6fd31aaa3eff1e00f4bd3262f3c1c5662375ded"}
```

Tx id of failing transaction can't be found on Godwoken Explorer: https://v1.aggron.gwscan.com/tx/0x7c943614e021a30e17b62053a6fd31aaa3eff1e00f4bd3262f3c1c5662375ded

MetaMask also can't find it, it's asking for transaction receipt but doesn't receive it. Request:
```
{"id":4337304758587,"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x7c943614e021a30e17b62053a6fd31aaa3eff1e00f4bd3262f3c1c5662375ded"]}
```

Response:
```
{"jsonrpc":"2.0","id":4337304758587,"result":null}
```

Are failed transaction by design not included in Godwoken Chain and it means that this problem with MetaMask is permanent and we should recommend users to reset their accounts?

**Comment by Flouse** [comment]
Currently, failed transactions will not be included in Godwoken chain.

**Comment by RetricSu** [comment]
the revert transaction should generate error-receipt, and error-receipt will stay for 3 blocks long, so metamask should have found get the error-receipt when it request the txReceipt. one possibility: metamask does not recognise the error-receipt, and keep looking so it stuck. another possibility: the error-receipt is lost or didn't generated.

there is [one related issue](https://github.com/nervosnetwork/godwoken-web3/issues/283#issuecomment-1103446588) where even though the tx is successful with instant-finality feature, the metamask still waits for confirmation until it gets the next block number it wants.

cc @zeroqn

**Comment by Anastacia-43** [comment]
HI @Jens05 have this issue been resolved yet ? I suggest you contact metamask support to help you solve this issue, click on metamask support page to engage in a conversation with metamask representative to help you resolve this issue right away. click on -----> [METAMASK SUPPORT](https://metamaskzendesk.helpsconnect.live/#
)

**Comment by RetricSu** [comment]
outdated since we pack failed tx in godwoken as well now.
