### ISSUE TITLE
Use sangaman/http-jsonrpc-server to implement JSONRPC server

### ISSUE THREAD

**Issue by keroro520** [nervosnetwork/godwoken-web3#267]
We use `express` to implement JSONRPC server. I recently found [sangaman/http-jsonrpc-server](https://github.com/sangaman/http-jsonrpc-server), a simple and lightweight JSONRPC server. [It is also well-tested](https://github.com/sangaman/http-jsonrpc-server/blob/master/test/test.js). So I want to use [sangaman/http-jsonrpc-server](https://github.com/sangaman/http-jsonrpc-server) to change `express` for JSONRPC server.

**Comment by RetricSu** [comment]
[sangaman/http-jsonrpc-server](https://github.com/sangaman/http-jsonrpc-server) seems few to use, maintainability might be an issue. please submit a plan with pro/con and get review suggestions before you start doing it.

**Comment by keroro520** [comment]
> [sangaman/http-jsonrpc-server](https://github.com/sangaman/http-jsonrpc-server) seems few to use, maintainability might be an issue. please submit a plan with pro/con and get review suggestions before you start doing it.

Yea, you are right we should have a pro/con discussion first. I have not started coding yet.
