### ISSUE TITLE
Godwoken RPC returns 'Error -32600 (Invalid request)'

### ISSUE THREAD

**Issue by fsy412** [nervosnetwork/godwoken-web3#313]
I am working on a Go code to monitor the block tx status on chain.
The code is working fine on both ethereum and bsc chains.
When switch to Godwoken RPC endpoint(https://godwoken-testnet-web3-v1-rpc.ckbapp.dev/), it simply return 'Error -32600 (Invalid request)'.
the below RPC method is called in the code
    GetCurrentBlockNum
    GetBlockByNum
    GetTransactionReceip
bsc log:
![bsc](https://user-images.githubusercontent.com/4018096/166940134-35ebd255-8ade-4546-892c-9b7ea2814a60.png)
godwoken log:
![godwoken](https://user-images.githubusercontent.com/4018096/166940161-6d143d4e-9d4e-43e7-8b23-c24c0c0458ae.png)

**Comment by RetricSu** [comment]
can you print out the raw RPC method and params? I mean like 

```sh
curl http://localhost:3000 -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method":"gw_get_script_hash_by_registry_address", "params": ["0x0200000014000000599f0453dbe60439c58feb4c6f8ed428fc6b7ae3"], "id"
: 1}'
```

right now it is all wrapped in your go code, it doesn't have much useful info to debug with

**Comment by fsy412** [comment]
# Verbose log

## BSC:
api https://data-seed-prebsc-1-s1.binance.org:8545/
{"id":1,"jsonrpc":"2.0","method":"eth_blockNumber","params":null}
watcher.latestBlockNum() 19059759 <nil>
watcher.LatestSyncedBlockNum() 0
{"id":1,"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x122d42f",true]}
adding new block: 19059759
{"id":1,"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xac21b85767bc6a9037bf57bb3d13561c102b70db9588f778f52d3d84ef714116"]}
{"id":1,"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xaa9fe68c8753d2426bd924db41f133bc4ae0ad35cc0daf8c78b774c906442db9"]}
{"id":1,"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xd8078e28982ee6877ab4042ab9620adfb86bef2187e75d83f423b7d4836d12d0"]}
{"id":1,"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x5162e593861adda6925ff1e13ac842226f29a1143bf8cc7eadfe31a7078eb59a"]}
{"id":1,"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x5c4b6ecc5340e8f079a34a9a329f0b4b06f1e8d4b1aa053a7177a8ce75bcae78"]}
{"id":1,"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0x0c51f00285a620a6e03f26d74126207bc1a51a47e2a45dd2a2a8f542b52089b4"]}
{"id":1,"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xbb324177067dee2e5a60fac4244a8d1314ad293da660d468cb75116a50e22ffc"]}
{"id":1,"jsonrpc":"2.0","method":"eth_blockNumber","params":null}
INFO[2022-05-06T11:43:28+08:00] TxHandlerFunc recv: tx 0xbb324177067dee2e5a60fac4244a8d1314ad293da660d468cb75116a50e22ffc, txReceipt true 
INFO[2022-05-06T11:43:28+08:00] TxHandlerFunc recv: tx 0xd8078e28982ee6877ab4042ab9620adfb86bef2187e75d83f423b7d4836d12d0, txReceipt true 
INFO[2022-05-06T11:43:28+08:00] TxHandlerFunc recv: tx 0x0c51f00285a620a6e03f26d74126207bc1a51a47e2a45dd2a2a8f542b52089b4, txReceipt true 
INFO[2022-05-06T11:43:28+08:00] TxHandlerFunc recv: tx 0xac21b85767bc6a9037bf57bb3d13561c102b70db9588f778f52d3d84ef714116, txReceipt true 
INFO[2022-05-06T11:43:28+08:00] TxHandlerFunc recv: tx 0x5162e593861adda6925ff1e13ac842226f29a1143bf8cc7eadfe31a7078eb59a, txReceipt true 
INFO[2022-05-06T11:43:28+08:00] TxHandlerFunc recv: tx 0x5c4b6ecc5340e8f079a34a9a329f0b4b06f1e8d4b1aa053a7177a8ce75bcae78, txReceipt true 
INFO[2022-05-06T11:43:28+08:00] TxHandlerFunc recv: tx 0xaa9fe68c8753d2426bd924db41f133bc4ae0ad35cc0daf8c78b774c906442db9, txReceipt true 
watcher.latestBlockNum() 19059759 <nil>
watcher.LatestSyncedBlockNum() 19059759
no new block to sync, sleep for 3 secs

## Godwoken:
api https://godwoken-testnet-web3-v1-rpc.ckbapp.dev
2022/05/06 11:48:38 eth_blockNumber
Request: {"id":1,"jsonrpc":"2.0","method":"eth_blockNumber","params":null}
Response: {"jsonrpc":"2.0","id":null,"error":{"code":-32600,"message":"Invalid request"}}

2022/05/06 11:48:39 eth_blockNumber
Request: {"id":1,"jsonrpc":"2.0","method":"eth_blockNumber","params":null}
Response: {"jsonrpc":"2.0","id":null,"error":{"code":-32600,"message":"Invalid request"}}

**Comment by RetricSu** [comment]
there is a compatibility issue with RPC params being null, you can use the following as a workaround:

```sh
Request: {"id":1,"jsonrpc":"2.0","method":"eth_blockNumber","params": []}
```

we will fire a fix pr to allow params to be null. ref: https://www.jsonrpc.org/specification#parameter_structures

**Comment by RetricSu** [comment]
we use jayson as middleware, and this line of code will fire the error https://github.com/tedeh/jayson/blob/master/lib/utils.js#L331

fixed pr: 

- https://github.com/nervosnetwork/godwoken-web3/pull/315
