### ISSUE TITLE
How can I get  eth_tx_hash through gw_tx_hash

### ISSUE THREAD

**Issue by zmcNotafraid** [nervosnetwork/godwoken-web3#317]
I already know a gw tx hash and it is a polyjuice transaction.I want to get it's eth_tx_hash.
Before I query `eth_getBlockByHash` and get all eth_tx_hashs,.but if this block have other type tx(eg. eth_addr_reg), eth_tx_hashs could not map with block's gw_tx_hash because the length is not same.
So it's there a rpc method for query eth_tx_hash by gw_tx_hash? Or `eth_getBlockByHash `returns transactions order is fixed relative to `gw_get_block_by_hash `returns transactions

**Comment by RetricSu** [comment]
right now we don't have such API because the gw_tx_hash is supposed to be hidden from the user. one hard way to get such  info might require converting Godwoken tx object into Ethereum tx object, then RLP encoding it to [calc the hash](https://github.com/nervosnetwork/godwoken-web3/blob/main/packages/api-server/src/convert-tx.ts#L49-L54)

we can discuss if such an API should be added.

**Comment by zmcNotafraid** [comment]
I want to check my previous way is correct or not?
Such as:
```
block 100 have 4 txs, 
`gw_get_block_by_hash ` returns 4 gw_tx in order [eth_addr_reg_gw_hash_a, polyjuice_gw_hash_a, plyjuice_gw_hash_b, polyjuice_gw_hash_c]
`eth_getBlockByHash  `returns 3 transactions in order [poyjuice_eth_hash_A, polyjuice_eth_hash_B, polyjuice_eth_hash_C].
So I can map them that polyjuice_gw_hash_a's eth_hash is poyjuice_eth_hash_A and plyjuice_gw_hash_b's eth hash is polyjuice_eth_hash_B
```

**Comment by Flouse** [comment]
Here is another way:

If you have a Godwoken readonly node running with web3-indexer service,
then you could query `gw_tx_hash` and `eth_tx_hash` from `TABLE transactions` in the indexer PostgreSQL DB.

Hope it helps.

see：
https://github.com/nervosnetwork/godwoken-info/blob/main/testnet_v1/docker-compose.yml#L61-L77

**Comment by RetricSu** [comment]
> I want to check my previous way is correct or not? Such as:
> 
> ```
> block 100 have 4 txs, 
> `gw_get_block_by_hash ` returns 4 gw_tx in order [eth_addr_reg_gw_hash_a, polyjuice_gw_hash_a, plyjuice_gw_hash_b, polyjuice_gw_hash_c]
> `eth_getBlockByHash  `returns 3 transactions in order [poyjuice_eth_hash_A, polyjuice_eth_hash_B, polyjuice_eth_hash_C].
> So I can map them that polyjuice_gw_hash_a's eth_hash is poyjuice_eth_hash_A and plyjuice_gw_hash_b's eth hash is polyjuice_eth_hash_B
> ```
> 
> @RetricSu

I think the more robust way is to use @Flouse 's [answer](https://github.com/nervosnetwork/godwoken-web3/issues/317#issuecomment-1119455915) or consider adding a new API like `poly_getEthTxHashByGwTxHash` ?
