### ISSUE TITLE
transfer failed from reigister addresss to an unreigister address

### ISSUE THREAD

**Issue by xiefei1024** [nervosnetwork/godwoken-web3#324]
transfer failed from reigister addresss to an unreigister address
test scritps:
        it("to address is not register address", async () => {
            console.log("begin")
            let tx = await ethers.provider.send("eth_sendTransaction", [{
                "from": "0x85c62906a06b37389dc7c3a3ffa8687f21ea1090", //reigister addresss
                "to":"0x6510bbb94414b2F93458d23992714BAeA69F8c82", // unreigister address
                "gasPrice": "0x1",
                "data": fallbackAndReceiveContract.bytecode
            }]);
            let response = await getTxReceipt(ethers.provider,tx,100)
            console.log("response:",response)
        }).timeout(150000)
error:
ProviderError: UNPREDICTABLE_GAS_LIMIT: to id missing! toAddress: 0x6510bbb94414b2F93458d23992714BAeA69F8c82

**Comment by RetricSu** [comment]
https://github.com/nervosnetwork/godwoken-web3/blob/compatibility-breaking-changes/docs/compatibility.md#1-transactionto-must-be-a-contract-address pls use erc20 to transfer eoa to eoa

**Comment by xiefei1024** [comment]
I used https://godwoken-betanet-v1.ckbapp.dev/

**Comment by RetricSu** [comment]
to address must be a contract address https://github.com/nervosnetwork/godwoken-web3/blob/compatibility-breaking-changes/docs/compatibility.md#1-transactionto-must-be-a-contract-address

**Comment by xiefei1024** [comment]
I used V1.1 network

**Comment by keroro520** [comment]
@RetricSu We could make error messages inform users about the compatibility feature and provide a link to the recommended workaround. Let's keep this issue open and try to improve the response message.

**Comment by xiefei1024** [comment]
ok

**Comment by RetricSu** [comment]
> @RetricSu We could make error messages inform users about the compatibility feature and provide a link to the recommended workaround. Let's keep this issue open and try to improve the response message.

yea, we already have one https://github.com/nervosnetwork/godwoken-web3/blob/compatibility-breaking-changes/packages/api-server/src/methods/gw-error.ts#L246 some other places missing should be added as well.

**Comment by xiefei1024** [comment]
please closed
