### ISSUE TITLE
The eth_estimateGas interface return 0x0 while transfer ckb from eoa address to a contract address

### ISSUE THREAD

**Issue by xiefei1024** [nervosnetwork/godwoken-web3#335]
The eth_estimateGas interface return 0x0 while transfer ckb from eoa address to contrace address
The parameters ：
{
  jsonrpc: '2.0',
  method: 'eth_estimateGas',
  params: [
    {
      from: '0x902981453C14df4875D3Af110A0021580FB6c800',
      to: '0xc4e616B5694cfF04caE5b9290E6868C2beB3cd6f',
      gasPrice: '0x1',
      gas: '0x11'
    }
  ],
  id: 6
}
The return result:
{ jsonrpc: '2.0', id: 6, result: '0x0' }
tx is:...... 0x0

**Comment by RetricSu** [comment]
https://github.com/nervosnetwork/godwoken-web3/commit/bfe3dfea70d119574e879de5ce3fa74dad7690fa web3 fix
