### ISSUE TITLE
The eth_estimateGas interface should return error and fail  while value parameter and data parameter exited in the same time

### ISSUE THREAD

**Issue by xiefei1024** [nervosnetwork/godwoken-web3#336]
The parameteres
{
  jsonrpc: '2.0',
  method: 'eth_estimateGas',
  params: [
    {
      from: '0x902981453C14df4875D3Af110A0021580FB6c800',
      to: '0xc4e616B5694cfF04caE5b9290E6868C2beB3cd6f',
      gasPrice: '0x1',
      gas: '0x11',
      value: '0x1',
      data: '0xa9059cbb000000000000000000000000ca84b63f64991bea7f03b1f3500cff9b0f0e08f60000000000000000000000000000000000000000000000000000000000000001'
    }
  ],
  id: 6
}
The return:
{ jsonrpc: '2.0', id: 6, result: '0xafef' }
tx is:...... 0xafef

**Comment by RetricSu** [comment]
I use infura to test ethereum mainnet

```sh
{
    "jsonrpc": "2.0",
    "method": "eth_estimateGas",
    "params": [
        {
            "from": "0x439640DbA3Bc8C662cF0F7E060E3e5a11E8ca908",
            "to": "0x768249aC5ED64517C96c16e26B7A5Aa3E9334217",
            "data": "0xa9059cbb000000000000000000000000ca84b63f64991bea7f03b1f3500cff9b0f0e08f60000000000000000000000000000000000000000000000000000000000000001",
            "value": "0x1"
        },
        "latest"
    ],
    "id": 0
}
```

--

```sh
{
    "jsonrpc": "2.0",
    "id": 0,
    "result": "0x5444"
}
```

why should it return error and fail while data and value exit? I didn't find the spec for such behavior. can you identify the source?
