### ISSUE TITLE
Transferring CKB as ERC20 to unregistered address doesn't create an account

### ISSUE THREAD

**Issue by Kuzirashi** [nervosnetwork/godwoken-web3#337]
I sent 1 CKB as ERC20 token on Layer 2 from 0xd173313a51f8fc37bcf67569b463abd89d81844f to 0x2B29C810bf9f8c2FD2e05B950a8afceA821F2822 as seen in transaction https://gw-explorer.nervosdao.community/tx/0x1656ff8cc46641e4c4e648ff7dfcc0b6c8e112676662a37e714a900efc0d4902/token-transfers

0xd173313a51f8fc37bcf67569b463abd89d81844f  is registered address.
0x2B29C810bf9f8c2FD2e05B950a8afceA821F2822 is unregistered address.

![image](https://user-images.githubusercontent.com/4950658/168148712-93e7bf7b-d51c-4394-8f0d-32985318e353.png)

However when I try to do a smart contract READ or WRITE from the account that received tokens (unregistered address) I get an error:
```
Error: Returned error: from id not found by from address: 0x2b29c810bf9f8c2fd2e05b950a8afcea821f2822, have you deposited?
    at Object.ErrorResponse (/home/kuzi/projects/layer2-evm-documentation/code-examples/5-erc20-proxy/node_modules/web3/node_modules/web3-core-helpers/lib/errors.js:28:19)
```

The token transfer is visible in block explorer though:
![image](https://user-images.githubusercontent.com/4950658/168149055-7c10940f-680b-4e19-8def-9819a5e54498.png)

I would expect to be able to do calls and send transaction on the chain after receiving pCKB on Layer 2 using RECEIVER account.

---

Is this on purpose that CKB transfer on Godwoken doesn't create an account for the user? I think it could make onboarding easier if user could start using his account after receiving funds straight on Layer 2 instead of going to Layer 1 to transfer tokens to his deposit address.

Would it be accurate to describe this as on L2 you can interact with any EOA account even if it doesn't exist, but in order for the owner of that EOA account to interact with it, it must be "activated" using the L1 create account procedure?

**Comment by Flouse** [comment]
> I would expect to be able to do calls and send transaction on the chain after receiving pCKB on Layer 2 using RECEIVER account.

Maybe, Web3 could try to register a new Godwoken account using `meta_contract` when the tx.from is not registered.

**Comment by Flouse** [comment]
### Update
Let's say there is a eth_address with Layer2_pCKB_balance > 0. When someone use this eth_address as from_address to send a transaction, Godwoken will register it automatically.

This is a new feature we are designing.
It means that a DApp developer or user should not be worry about creating an account of Godwoken.

**Comment by Flouse** [comment]
## Related PRs
- https://github.com/nervosnetwork/godwoken/pull/710
- https://github.com/nervosnetwork/godwoken-web3/pull/430

**Comment by Flouse** [comment]
- [ ] New releases @RetricSu @Flouse

**Comment by Flouse** [comment]
- https://github.com/nervosnetwork/godwoken-info/pull/50
   deployed on Godwoken testnet_v1
   
known issue:
- https://github.com/nervosnetwork/godwoken-web3/issues/468 (fixed)

**Comment by Flouse** [comment]
- https://github.com/nervosnetwork/godwoken-info/pull/52
  deployed on Godwoken mainnet_v1

```bash
curl https://v1.mainnet.godwoken.io/rpc -X POST \
  -H "Content-Type: application/json" \
  -d '{"jsonrpc": "2.0", "method":"poly_version", "params": [], "id": 1}'

# Result
{"jsonrpc":"2.0","id":1,"result":{"versions":{"web3Version":"1.5.2-rc1","web3IndexerVersion":"1.5.2-rc1","godwokenVersion":"1.4.0-rc4 17a0cb5"},"nodeInfo":{...
```
