### ISSUE TITLE
Merge "compatibility-breaking-changes" into "main" branch

### ISSUE THREAD

**Issue by keroro520** [nervosnetwork/godwoken-web3#340]

**Comment by keroro520** [comment]
Because the "main" branch is rarely updated, I look through the updates from the common commit of the "main" and "compatibility-breaking-changes" branches:

```
$ git merge-base main compatibility-breaking-changes
89b36c8c1214d5dcd849bba0f47c216fa72d5053

$ tig 89b36c8c1214d5dcd849bba0f47c216fa72d5053..main
```



Then I found that there are 3 updates that do not exist in the "compatibility-breaking-changes" branch: 

* [[feat: add cache for executeRawL2Tx #156](https://github.com/nervosnetwork/godwoken-web3/pull/156)](https://github.com/nervosnetwork/godwoken-web3/pull/156) 
* [[fix: redis subscribe stuck when executeResult failed #1733](https://github.com/nervosnetwork/godwoken-web3/pull/173)](https://github.com/nervosnetwork/godwoken-web3/pull/173)
* [[fix(v0): support blockTag in poly_executeRawL2Transaction #226](https://github.com/nervosnetwork/godwoken-web3/pull/226)](

**Comment by RetricSu** [comment]
great job, those 3 commits are all related to poly_executeRawL2Transaction which is deprecated in v1 version. 

so I think we are clean with compatible branch?
