### ISSUE TITLE
Improve RPC response message

### ISSUE THREAD

**Issue by keroro520** [nervosnetwork/godwoken-web3#341]
## Error Kinds

As it is enough to distinguish error types according to the `Error::name`, I plan to remove all the sub-error types, except [`RpcError`](https://github.com/nervosnetwork/godwoken-web3/blob/4bf20d5c0f25cd85a90b3fccd03129797b69911e/packages/api-server/src/methods/error.ts#L13-L24)(renamed to `AppError`), and then uses a unified error type `AppError` instead:

- `AppError::name` denotes the error kind
- `AppError::stack` , same as `Error::stack`
- `AppError::message`, demonstrates when happened
- `AppError::code` is corresponding to `AppError::message`
- `AppError::data` provides the context when the error occurs, such as address, balance, and underlying error

```typescript
# in error.ts
export class AppError extends Error implements JSONRPCError {
  code: number;
  data?: object;
  
  constructor(kind: ErrorKind, message: string, data?: object) {
    super(message);
    this.name = kind.name;
    this.code = kind.code;
    this.data = data;
  }
}

export interface ErrorKind {
  // error code
  code: number,
  // error name
  name: string,
}

const ERRORS = Object.freeze({
  HTTP_CONNECTION_RESET: {
    code: 1234,
    name: "HTTP connection reset"
  } as ErrorKind,
});
```

## Usage:

```typescript
import { ERRORS } from "./error.ts";

throw new AppError(
  ERRORS.HTTP_CONNECTION_RESET,
  "Error calling gw_get_withdrawal",
  {
    error,
    withdrawalHash,
  }
);

// function parseGwError
throw new AppError(
  ERRORS.GW_ERROR,
  "",
  {
    decodedReturnData,
    polyjuiceLogs,
    accountId,
    serviceFlag,
  }
);
```

## Handle Errors

```typescript
function middleware() {
	...
     try {
	...
     } catch (error: any) {
        if (error instanceof AppError) {
           throw error;
     } else {
      // should never happen
      console.error("unknown error:", error);
      throw new AppError(ERRORS.UNKNOWN, `Error handling ${method}`, { error });
     }
}
```

## Generate Error documentation

Travels the `ERRORS` object.

## Related issues
- https://github.com/nervosnetwork/godwoken-web3/issues/423

**Comment by keroro520** [comment]
Updated:
- Complete the design for error handling https://github.com/nervosnetwork/godwoken-web3/issues/341#issue-1236736226

**Comment by keroro520** [comment]
Updated:
- PR https://github.com/nervosnetwork/godwoken-web3/pull/351 implement the 1st part, "Error Kinds"
- PR https://github.com/nervosnetwork/godwoken-web3/pull/352 implement the 2nd and 3rd parts, "Usage", "Handle Errors"

**Comment by keroro520** [comment]
Some references:
- https://github.com/MetaMask/eth-rpc-errors/blob/main/src/error-constants.ts
- https://github.com/MetaMask/eth-rpc-errors/blob/main/test/errors.js

**Comment by keroro520** [comment]
@classicalliu @RetricSu I need you to review this design for me. Let me know your opinions. Thanks~

**Comment by RetricSu** [comment]
> @classicalliu @RetricSu I need you to review this design for me. Let me know your opinions. Thanks~

good job, I have written thoughts in the review suggestion

**Comment by classicalliu** [comment]
> @classicalliu @RetricSu I need you to review this design for me. Let me know your opinions. Thanks~

LGTM

**Comment by classicalliu** [comment]
One more thing, what's the main advantage over inheritance ?

**Comment by keroro520** [comment]
> One more thing, what's the main advantage over inheritance?

Do you mean defining `AppError` vs using `JSONRPCError` directly?

I think the error stack is useful for us. So I have to merge the standard `Error` and `JSONRPCError`, or say, inherit from both `Error` and `JSONRPCError`.

**Comment by classicalliu** [comment]
> > One more thing, what's the main advantage over inheritance?
> 
> Do you mean defining `AppError` vs using `JSONRPCError` directly?
> 
> I think the error stack is useful for us. So I have to merge the standard `Error` and `JSONRPCError`, or say, inherit from both `Error` and `JSONRPCError`.

```typescript
export class AppError extends Error implements JSONRPCError {
  code: number;
  data?: object;
  
  constructor(name: string, code: number, message: string, data?: object) {
    super(message);
    this.name = kind.name;
    this.code = kind.code;
    this.data = data;
  }
}

export class HttpConnectionResetError extends AppError {
  constructor(message: string, data?: object) {
    super("HTTP connection reset", 1234, message, data);
  }
}

// And when use
throw new HttpConnectionResetError(
  "Error calling gw_get_withdrawal",
  {
    error,
    withdrawalHash,
  }
);
```

Like this

**Comment by keroro520** [comment]
> 

One thing I learn from [this post](https://stackify.com/node-js-error-handling) is that a uniform error type is enough most of the time. Specific error types are often redundant, for example, the type name(`HttpConnectionResetError`) and the `error.name`("HTTP connection reset") describe the same thing. That's why I prefer uniform error type. @classicalliu

**Comment by classicalliu** [comment]
> > 
> 
> One thing I learned from [this post](https://stackify.com/node-js-error-handling)(chapter "Error Object" and "Anatomy of an error object") is that a uniform error type is usually enough. In many case, specific error types are often redundant, for example, both the type name(`HttpConnectionResetError`) and the `error.name`("HTTP connection reset") describe the same thing. That's why I prefer a uniform error type. @classicalliu

We can remove `name` property

```typescript
// error
export class AppError extends Error {
  code: number;
  data?: object;
  
  constructor(code: number, message: string, data?: object) {
    super(message);
    this.code = code;
    this.data = data;
  }
}

export class HttpConnectionResetError extends AppError {
  constructor(message: string, data?: object) {
    super(1234, message, data);
  }
}

// usage
throw new HttpConnectionResetError(
  "Error calling gw_get_withdrawal",
  {
    error,
    withdrawalHash,
  }
);

// middleware
function middleware() {
	...
     try {
	...
     } catch (error: any) {
        if (error instanceof AppError) {
           throw error;
       } else {
        // should never happen
        console.error("unknown error:", error);
        throw new UnknownError(`Error handling ${method}`, { error });
       }
    }
}
```

Seems more clear, add methods such as `addContext` defined in `AppError` can be override if need.
So I don't understand what's the main benefit of combination than inheritance ?

**Comment by classicalliu** [comment]
Just for prefer message like `HTTP connection reset: Error calling gw_get_withdrawal` than `HttpConnectionResetError: Error calling gw_get_withdrawal` ?

**Comment by keroro520** [comment]
In my opinion, both the code structures are clear enough, and both are common. No redundant information; error code and error kind remain in the same place; most importantly all error kinds can be cast to a uniform `AppError` to  make error handling easy.

Next, I would like to discuss my understanding of inheritance. "A inherits from I, B inherits from I too" is generally used when both A and B want to reuse I's logic while in the meantime, A and B have their own logic, so they have to define two new classes to implement their own logic.

As you can see, all of our errors can be represented by a tuple `(code, message, context)` with no custom logic. So I think a uniform `AppError` plus an error table is more simple than a `AppError` plus many inherited types.

Besides, one more thing, I personally like collecting all the error definitions into one table, because that makes users easy to look up.

@classicalliu

**Comment by keroro520** [comment]
> Just for prefer message like `HTTP connection reset: Error calling gw_get_withdrawal` than `HttpConnectionResetError: Error calling gw_get_withdrawal` ?

"HTTP connection reset" and "HttpConnectionResetError" are the same for me. :)
