### ISSUE TITLE
Adjust the `BODY_PARSER_LIMIT`

### ISSUE THREAD

**Issue by keroro520** [nervosnetwork/godwoken-web3#347]
To prevent DDoS attacks, we must limit the transaction size without the size limit of `tx.data` (ref https://github.com/nervosnetwork/godwoken-web3/pull/344).

We already archive this by limiting the request body size, [`BODY_PARSER_LIMIT = 100mb`](https://github.com/nervosnetwork/godwoken-web3/blob/100d6e7ff4c63d06fbe2b448924f2bf4e757c6bd/packages/api-server/app.js#L22-L24). While I think the value is too large.

[Geth defines a similar size limit`txMaxSize = 128KB`](https://github.com/ethereum/go-ethereum/blob/b3b8b268eb585dfd3c1c9e9bbebc55968f3bec4b/core/tx_pool.go#L49-L53).

**Comment by classicalliu** [comment]
How about send several transactions in one RPC, such as 
`[{ id: 1, jsonrpc: "2.0", method: "eth_sendRawTransaction", params: [...] }, { id: 2, jsonrpc: "2.0", method: "eth_sendRawTransaction", params: [...] }]`
