### ISSUE TITLE
Inconsistent transactions with same input data

### ISSUE THREAD

**Issue by moonthoon** [nervosnetwork/godwoken-web3#348]
Here are two transactions both with the same input data however both vary in their gas limit.

I will refer to the transactions as follows: 

**TX-A:** 
https://v1.betanet.gwscan.com/tx/0x953281f6f87d696535febb0247da66294ca0ad6e96d32658660e0ed2af0dae24

**TX-B:** 
https://v1.betanet.gwscan.com/tx/0x8d4e8de4b86e3c88982d00cf97de8b53a3e745b6f2de4ef61b2f835c6d4f27a7

Both transactions were created using Ether JS + Metamask on my frontend application.  TX-A uses the gas limit automatically calculated by Ether JS. For TX-B, I manually set the gas limit to a large number. From looking at both transactions you can see they were both successful however in TX-A there is no ERC20 transfer. The interesting thing is that the gas used in TX-B is the same as the gas limit in TX-A yet the transactions both differ.

This transaction should call a method on my smart contract that transfers tokens from the user's wallet to the contract (I had approved the token for use by the contract beforehand).

I don't believe this should be happening, surely TX-A should've failed because it didn't transfer the tokens? 

Here is a screenshot of the method I am calling on the smart contract:
<img width="745" alt="Screenshot 2022-05-18 at 17 34 04" src="https://user-images.githubusercontent.com/101889315/169095279-97d86923-3bb1-4116-903f-3fbb83a5f4ab.png">

This issue is causing a big problem on my frontend application because any "write" smart contract function I call from the frontend requires me to manually increase the gas limit (and gas price because Metamask is defaulting it to 1e-9)

**Comment by jjyr** [comment]
Hi, the both transaction are failed. You can query the receipt of the transaction.

```
curl --location --request POST 'https://godwoken-testnet-v1.ckbapp.dev' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "id": "2",
    "method": "eth_getTransactionReceipt",
    "params": [
        "0x8d4e8de4b86e3c88982d00cf97de8b53a3e745b6f2de4ef61b2f835c6d4f27a7"
    ]
}'
```

I think the GWscan will show transaction status on the UI in the next release.

**Comment by jjyr** [comment]
Can you try to increase the gas limit of the transaction until it's status return 0?

I think the estimate_gas RPC returns incorrect gas_limit.

**Comment by moonthoon** [comment]
> I think the estimate_gas RPC returns incorrect gas_limit and status, can you provide a test case to reproduce this error?

Sure thing, I'll put up a git repo shortly

**Comment by moonthoon** [comment]
@jjyr I have added a test case here https://github.com/moonthoon/godwoken-issue-348

**Comment by classicalliu** [comment]
We have update the testnet, can you try again to check this problem persists ?

**Comment by classicalliu** [comment]
Test transactions:
https://v1.betanet.gwscan.com/zh-CN/tx/0x67e6f76fb4874b9e4ea0c73d24a180440384585cdf49941e0cddb1354f24f5ea
https://v1.betanet.gwscan.com/zh-CN/tx/0xaf15a5d7559030bddb9da264746850d7bc542f82314f2dbf2b167244f94c5905

**Comment by moonthoon** [comment]
> We have update the testnet, can you try again to check this problem persists ?

Thanks! I'll try it out on my end later today

**Comment by worldtokenben** [comment]
@classicalliu I've just tested it on my dApp and it works perfectly, thank you!

**Comment by moonthoon** [comment]
@classicalliu works perfectly on my dApp! Thank you 😄

**Comment by moonthoon** [comment]
<img width="1168" alt="Screenshot 2022-05-27 at 23 14 35" src="https://user-images.githubusercontent.com/101889315/170795514-5d683828-31f5-48f3-abf6-6134442a3b90.png">
One thing I did notice is that GwScan doesn't take care of decimals when displaying how much was transferred

**Comment by Flouse** [comment]
> <img alt="Screenshot 2022-05-27 at 23 14 35" width="1168" src="https://user-images.githubusercontent.com/101889315/170795514-5d683828-31f5-48f3-abf6-6134442a3b90.png">
> 
> One thing I did notice is that GwScan doesn't take care of decimals when displaying how much was transferred

cc @Keith-CY

**Comment by Keith-CY** [comment]
> <img alt="Screenshot 2022-05-27 at 23 14 35" width="1168" src="https://user-images.githubusercontent.com/101889315/170795514-5d683828-31f5-48f3-abf6-6134442a3b90.png">
> 
> One thing I did notice is that GwScan doesn't take care of decimals when displaying how much was transferred

The value isn't parsed with decimal because the token info is missing, so the value is raw and without a symbol

Here's an example that includes transfer records of a known token and two unknown tokens
![image](https://user-images.githubusercontent.com/7271329/170856920-deb74447-abc4-4ec2-9a3e-2753ddb0e62b.png)

YOK has been registered so its value is displayed in amount format while the other two are not registered so raw data are shown.

Token info can be submitted in https://github.com/Magickbase/godwoken_explorer/issues/new/choose.
