### ISSUE TITLE
Inaccurate version returned by web3_clientVersion

### ISSUE THREAD

**Issue by Kuzirashi** [nervosnetwork/godwoken-web3#349]
![image](https://user-images.githubusercontent.com/4950658/169543602-fadac1c1-35a5-4359-ab7f-e0490e6cbcb4.png)

```
curl --location --request POST 'https://godwoken-testnet-v1.ckbapp.dev' \
--header 'Content-Type: application/json' \
--data-raw '{
    "jsonrpc": "2.0",
    "method": "web3_clientVersion",
    "params": [],
    "id": 0
}'
```

result:
```
Godwoken/v1.0.0-rc1/linux/node14.19.1
```

Expected:
Version returned `>= 1.1`?

**Comment by RetricSu** [comment]
https://github.com/nervosnetwork/godwoken-web3/pull/357

pls wait for testnet deployment.
