### ISSUE TITLE
[v1.1] get code of an unregister address return revert

### ISSUE THREAD

**Issue by gpBlockchain** [nervosnetwork/godwoken-web3#391]
env:https://godwoken-betanet-v1.ckbapp.dev

![image](https://user-images.githubusercontent.com/32102187/173035248-e9878f9a-1f40-4156-a408-dd8dd99ce023.png)
### solidity code 
```
function getOtherAddress(address addr) public view returns(address,uint256,bytes memory,uint256,bytes32){
        return (addr,addr.balance,addr.code,addr.code.length,addr.codehash);
    }
```
#### step :
1. deploy 
2. invoke getOtherAddress(un_register_account_address)

#### expected 
1. deploy success
2. invoke successful

#### repo
https://github.com/cryptape/evm-testing/blob/master/test/opcodes/blockchain/addressContract.js#L127-L134

**Comment by Flouse** [comment]
Which action triggered the REVERT?
- addr 
- addr.balance
- addr.code,
- addr.code.length
- addr.codehash

**Comment by gpBlockchain** [comment]
> * addr.balance

addr.balance

**Comment by Flouse** [comment]
Here is a similar [passed](https://github.com/nervosnetwork/godwoken-tests/runs/6854075312?check_suite_focus=true#step:6:174) test case about `unregEthAddr.balance`:
https://github.com/nervosnetwork/godwoken-tests/blob/develop/contracts/test/codehash.js#L87-L95

**Comment by gpBlockchain** [comment]
> Here is a similar [passed](https://github.com/nervosnetwork/godwoken-tests/runs/6854075312?check_suite_focus=true#step:6:174) test case about `unregEthAddr.balance`: https://github.com/nervosnetwork/godwoken-tests/blob/develop/contracts/test/codehash.js#L87-L95

sorry, addr.code
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/32102187/173268134-c6f7672d-b8e5-4711-9555-19d5eaf9b940.png">

**Comment by magicalne** [comment]
web3 logs:
```log
web3_1                            | [1] 2022-06-13T02:44:40.491Z [info]: Call gw rpc "gw_execute_raw_l2transaction" error: JSONRPCError: server error {"code":-32600,"message":"invalid exit code 83","data":{"tx_hash":"0x4ed0bbb5e5defbcad36c73ea41cd50377f8d8928547a8d0e71b5a2ed791a7bfd","block_number":"0x472","return_data":"0x000000000000000000000000db81d2b8154a10c6f25bc2a9225f403d954d0b65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","last_log":{"account_id":"0x21","service_flag":"0x2","data":"0xb513000000000000b513000000000000000000000000000000000000000000000000000000000000"},"exit_code":"0x53"}}
web3_1                            | [1] 2022-06-13T02:44:40.492Z [info]: Parse reason failed with return data: 0x000000000000000000000000db81d2b8154a10c6f25bc2a9225f403d954d0b65000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000a0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
web3_1                            | [1] 2022-06-13T02:44:40.492Z [error]: JSONRPC Server Error: [bound call] RpcError: success: reverted with custom error RpcError: success: reverted with custom error
```

Error code 83 means account not found.
