### ISSUE TITLE
godwoken-web3-indexer-prebuilds:Can't get script by script_hash

### ISSUE THREAD

**Issue by masayil** [nervosnetwork/godwoken-web3#405]
![image](https://user-images.githubusercontent.com/65291464/174431936-ce2c7bfc-6506-4d7a-8cfe-39b5f2c4679a.png)

**Comment by sopium** [comment]
Should be fixed by
- https://github.com/nervosnetwork/godwoken/pull/737

**Comment by masayil** [comment]
thx.

**Comment by Flouse** [comment]
> Should be fixed by
> 
> * [fix: read only nodes without p2p sync godwoken#737](https://github.com/nervosnetwork/godwoken/pull/737)

Image：
https://github.com/nervosnetwork/godwoken-docker-prebuilds/pkgs/container/godwoken-prebuilds/26181731?tag=1.2.2-rc1-202206210340
