### ISSUE TITLE
[BUG] The new account failed to transfer CKB as erc20 to the unregistered address

### ISSUE THREAD

**Issue by Dawn-githup** [nervosnetwork/godwoken-web3#467]
## **Version**
- Godwoken v1.5.0-rc1
- (RPC) https://godwoken-testnet-v1.ckbapp.dev/
  <details>
  <summary>command example</summary>

  ```sh
  git clone https://github.com/Dawn-githup/ERC20_Token.git

  run test/../demo
  ```
  </details>

## **Describe the bug**
The new account failed to transfer CKB as erc20 to the unregistered address

**To Reproduce**

1. Register a new account
2. Transfer CKB to new account
3. The new account can be used as a form account to transfer assets

**Expected behavior**

The newly registered new account can be used as a from to transfer assets

**Screenshots or Logs**

![image](https://user-images.githubusercontent.com/77844990/181203105-1ea804f3-2747-4029-a92a-1dfe2d7a9bfb.png)

**Comment by Dawn-githup** [comment]
- Error prompt java.lang.RuntimeException: Error processing transaction request: invalid argument 0: eth_sendRawTransaction parseRawTransactionData -> insufficient balance, require 450000000000000000000, got 5130100000000000000
- If I deposit 450ckb in my new account, it will succeed

**Comment by Dawn-githup** [comment]
- Error prompt java.lang.RuntimeException: Error processing transaction request: invalid argument 0: eth_sendRawTransaction parseRawTransactionData -> insufficient balance, require 450000000000000000000, got 5130100000000000000
- If I deposit 450ckb in my new account, it will succeed

**Comment by Flouse** [comment]
> * Error prompt java.lang.RuntimeException: Error processing transaction request: invalid argument 0: eth_sendRawTransaction parseRawTransactionData -> insufficient balance, require 450000000000000000000, got 5130100000000000000

## What is the gas_limit of this transaction? 
> https://github.com/Dawn-githup/ERC20_Token/blob/main/src/main/java/constant/Constant.java#L15

## Rule
new account balance >= tx tx.gas_limit * tx.gas_price + tx.value

**Comment by Dawn-githup** [comment]
I gave too much gas, resulting in consumption greater than new account balance
