### ISSUE TITLE
[BUG] "from id not found by from Address" when the transfer account balance is insufficient

### ISSUE THREAD

**Issue by Dawn-githup** [nervosnetwork/godwoken-web3#468]
## **Version**
- Godwoken v1.5.0-rc1
- (RPC) https://godwoken-testnet-v1.ckbapp.dev/

## **Describe the bug**
"from id not found by from Address" when the transfer account balance is insufficient

**To Reproduce**

1. Transfer balance is less than transfer amount
2. Send transaction

## **Expected behavior**

Give a clear prompt "insufficient account balance"

## **Screenshots or Logs**
{"jsonrpc":"2.0","id":16,"error":{"code":-32602,"message":"from id not found by from Address: 0x82b635775e2208a231e65b2fa4c3fbfacc42d408, have you deposited?"}}

**Comment by Flouse** [comment]
- https://github.com/nervosnetwork/godwoken-info/pull/52
  deployed on Godwoken mainnet_v1

```bash
curl https://v1.mainnet.godwoken.io/rpc -X POST \
  -H "Content-Type: application/json" \
  -d '{"jsonrpc": "2.0", "method":"poly_version", "params": [], "id": 1}'

# Result
{"jsonrpc":"2.0","id":1,"result":{"versions":{"web3Version":"1.5.2-rc1","web3IndexerVersion":"1.5.2-rc1","godwokenVersion":"1.4.0-rc4 17a0cb5"},"nodeInfo":{...
```
