### ISSUE TITLE
[BUG] "From id is missing" not showing for non registered account

### ISSUE THREAD

**Issue by m-bo-one** [nervosnetwork/godwoken-web3#480]
## **Version**
- Godwoken v1

```
curl -X POST --data '{"jsonrpc":"2.0","id":73,"method":"eth_call","params":[{"from":"0x2dA4a1f1cBdfa7F1D4E49c1db5d1AeE10d78A814","data": "0x9749c04a0000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000010000000000000000000000002da4a1f1cbdfa7f1d4e49c1db5d1aee10d78a814000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000002540be400","to":"0xA4b86a26A1C6751D9dc320416F30ff2fcbCdC946", "value": "0x2540be400"},"latest"]}' https://v1.mainnet.godwoken.io/rpc  -H "Content-Type: application/json"
```

## **Describe the bug**
When I try to execute a transaction from non registered wallet, but it has pCKB from smart contract native send/transfer/call, I do not receive error that account is not registered and all my transactions will be accepted by the node (but wont be executed)

**Expected behavior**

From id is missing

**Screenshots or Logs**

https://gw-mainnet-explorer.nervosdao.community/tx/0x791c3effd2eabc08f63b423f1512e8581b56e8b10948abfe3da90e610c5b1e1c/internal-transactions
https://gw-mainnet-explorer.nervosdao.community/tx/0x0bca6b9a8e3312b9b7a9ececb06b5839bc19dbd95d587181ee98e3f31bcf3be3/internal-transactions

two transactions where they have been sent as pCKB (as native) to 0x2dA4a1f1cBdfa7F1D4E49c1db5d1AeE10d78A814

**Comment by Flouse** [comment]
> https://gw-mainnet-explorer.nervosdao.community/tx/0x791c3effd2eabc08f63b423f1512e8581b56e8b10948abfe3da90e610c5b1e1c/internal-transactions https://gw-mainnet-explorer.nervosdao.community/tx/0x0bca6b9a8e3312b9b7a9ececb06b5839bc19dbd95d587181ee98e3f31bcf3be3/internal-transactions
> 
> two transactions where they have been sent as pCKB (as native) to 0x2dA4a1f1cBdfa7F1D4E49c1db5d1AeE10d78A814

Hi, @m-bo-one . Thanks for reporting this issue.
I have some questions:

1. What is this contract ([0xa4b86a26a1c6751d9dc320416f30ff2fcbcdc946](https://gw-mainnet-explorer.nervosdao.community/address/0xA4b86a26A1C6751D9dc320416F30ff2fcbCdC946/transactions)) ?
2. Why did they send msg.value to the above contract?
3. Why not use [pCKB_ERC20_Proxy](https://v1.gwscan.com/account/0x477f4bc34f5649e74d2c4a653fd428cfa7c5d3e75131619f19eb8b83e0560701?search=0x7538c85cae4e4673253ffd2568c1f1b48a71558a) contract to transfer pCKB?

**Comment by m-bo-one** [comment]
@Flouse 
1. Brief interface
```
// SPDX-License-Identifier: MIT
pragma solidity ^0.8.0;

interface ISend {
    function multiSendDiffEth(address payable[] memory recipients, uint256[] memory amounts) external payable;
}
```
The contract is used to make mass send from one of the build club

2. Because it is easier for them to make a mass send I suppose and should be cheaper.
3. I could recommend but will this auto-create a wallet on L1?

**Comment by Flouse** [comment]
> 3\. I could recommend but will this auto-create a wallet on L1?

Yes.
Now a Godwoken account will be activated simply when it has enough CKB and sends its first transaction.

see also: https://talk.nervos.org/t/godwoken-v1-4-release/6699#h-1-direct-account-creation-on-layer-2-2

**Comment by Flouse** [comment]
## Related issue
- https://github.com/nervosnetwork/godwoken-web3/issues/494 -> fixed

If you still encounter this issue, Please feel free to reopen it.
