### ISSUE TITLE
[BUG] The cost of sending Gas Used to an unregistered address is also 21000

### ISSUE THREAD

**Issue by Dawn-githup** [nervosnetwork/godwoken-web3#518]
## **Version**
- "web3Version":"1.7.0-rc1"
- (RPC) https://godwoken-testnet-v1.ckbapp.dev/

## **Describe the bug**
The cost of sending Gas Used to an unregistered address is also 21000

**To Reproduce**

1. transfer to unregistered address

## **Expected behavior**
It is expected that after the transfer is successful, an EOA account will be created for to_address, and the corresponding handling fee will be charged for the from id: 21000 (minimum transaction cost) + 25000 (account creation cost)

## **Screenshots or Logs**
Actual consumption: 21000

>>https://v1.betanet.gwscan.com/tx/0x7a17ce487e813b00421b651d267685e97315b30f3a50ef2a9a8458f1fa843361

**Comment by Dawn-githup** [comment]
```
$ rpc "https://godwoken-testnet-v1.ckbapp.dev" gw_get_script_hash_by_registry_address '["0x0200000014000000c7d2e37c3b38084c0aa2a698965860d7cbceb5b3"]' | json_pp
{
   "id" : 2,
   "jsonrpc" : "2.0",
   "result" : "0x8f0742ff7c7353d2158e54ee9dfed2be863e2ea0b7ac7e00003e06e183291593"
}

$ rpc "https://godwoken-testnet-v1.ckbapp.dev" gw_get_account_id_by_script_hash '["0x8f0742ff7c7353d2158e54ee9dfed2be863e2ea0b7ac7e00003e06e183291593"]'
{"jsonrpc":"2.0","id":2,"result":"0x10d14"}

$ rpc "https://godwoken-testnet-v1.ckbapp.dev" gw_get_nonce '["0x10d14"]'
{"jsonrpc":"2.0","id":2,"result":"0x0"}
```

**Comment by Flouse** [comment]
https://github.com/nervosnetwork/godwoken-polyjuice/releases/tag/1.4.1

**Comment by Flouse** [comment]
- https://github.com/nervosnetwork/godwoken-info/pull/64

**Comment by Dawn-githup** [comment]
> Testnet fixed
