### ISSUE TITLE
[BUG] eth_getLogs returns 0 logs if one of the topic have 0 logs

### ISSUE THREAD

**Issue by m-bo-one** [nervosnetwork/godwoken-web3#522]
## **Version**
- Godwoken v1

## **Describe the bug**
During multiple topics call for `eth_getLogs` it does not take into account from multiple topics, seems it checks the latest one from query and do not make a correct response.

Bug found by dex screener team during integration

**To Reproduce**

1.
```
curl -X POST https://v1.mainnet.godwoken.io/rpc --header 'content-type: application/json' --data-raw '{"jsonrpc":"2.0","id":44,"method":"eth_getLogs","params":[{"fromBlock":"0x1f62b","toBlock":"0x1f635","topics":["0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822"]}]}'
```
 1 topic: returns 5 logs - OK

2.
```
curl -X POST https://v1.mainnet.godwoken.io/rpc --header 'content-type: application/json' --data-raw '{"jsonrpc":"2.0","id":46,"method":"eth_getLogs","params":[{"fromBlock":"0x1f62b","toBlock":"0x1f635","topics":["0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67"]}]}'
```
1 topic: returns 0 logs - OK

3. 
```
curl -X POST https://v1.mainnet.godwoken.io/rpc --header 'content-type: application/json' --data-raw '{"jsonrpc":"2.0","id":48,"method":"eth_getLogs","params":[{"fromBlock":"0x1f62b","toBlock":"0x1f635","topics":["0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822","0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67"]}]}'
```
2 topics (both above): returns 0 logs, should return 5 - NOT OK

**Expected behavior**
Return 5 logs

**Actual behavior**
Return 0 logs

**Comment by RetricSu** [comment]
Topics are order-dependent.  To my understanding, The third case indicated that the first topic be `0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822` and the second topic be `0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67`, since there is no logs match for second topics, so returns 0 should be expected?

**Comment by keroro520** [comment]
It is expected behavior.

It seems that you want to use **optional topics**?

```
curl -X POST https://v1.mainnet.godwoken.io/rpc --header 'content-type: application/json' --data-raw '{"jsonrpc":"2.0","id":48,"method":"eth_getLogs","params":[{"fromBlock":"0x1f62b","toBlock":"0x1f635","topics":[["0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822","0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67"]]}]}'
```

it returns 5 logs.

**Comment by m-bo-one** [comment]
Agreed, this statement
```
curl -X POST https://v1.mainnet.godwoken.io/rpc --header 'content-type: application/json' --data-raw '{"jsonrpc":"2.0","id":48,"method":"eth_getLogs","params":[{"fromBlock":"0x1f62b","toBlock":"0x1f635","topics":[["0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822","0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67"]]}]}'
```
as or 0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822 or 0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67

this one
 ```
 curl -X POST https://v1.mainnet.godwoken.io/rpc --header 'content-type: application/json' --data-raw '{"jsonrpc":"2.0","id":48,"method":"eth_getLogs","params":[{"fromBlock":"0x1f62b","toBlock":"0x1f635","topics":["0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822","0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67"]}]}'
 ```
 0xd78ad95fa46c994b6551d0da85fc275fe613ce37657fb8d5e3d130840159d822 and 0xc42079f94a6350d7e6235f29174924f928cc2ac818eb64fed8004e115fbcca67 , if first zero then all zero, closing, thank you, just overlooked
